apiVersion: app/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world-pod
        image: docker pull hello-world:latest
        ports: 
        - containerPort: 80
